# Generated by Django 5.0.5 on 2024-07-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_recibo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recibo',
        ),
    ]
