# Generated by Django 5.0.5 on 2024-08-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_ordermembership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
