# Generated by Django 5.0.5 on 2024-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/profile_images/default_profile.png', upload_to='static/images/profile_images/'),
        ),
    ]
