# Generated by Django 5.0.5 on 2024-07-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymclass',
            old_name='image',
            new_name='image_class',
        ),
    ]
