# Generated by Django 5.0.5 on 2024-07-07 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymclass',
            name='schedule',
        ),
        migrations.AddField(
            model_name='gymclass',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
