# Generated by Django 5.0.5 on 2024-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_gymclass_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
