# Generated by Django 5.0.5 on 2024-10-21 11:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_gymclass_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='image_class',
            field=cloudinary.models.CloudinaryField(default='images/default_class.jpg', max_length=255, verbose_name='image_class'),
        ),
    ]
