# Generated by Django 5.0.5 on 2024-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_gymclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='image',
            field=models.ImageField(default='images/default_class.jpg', upload_to='static/class_images/'),
        ),
    ]
