# Generated by Django 5.0.5 on 2024-07-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='memberships.membership')),
            ],
        ),
    ]
