# Generated by Django 5.0.5 on 2024-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/profile_images/default-product-image.png', null=True, upload_to='static/images/product_images/'),
        ),
    ]
