# Generated by Django 5.0.5 on 2024-10-21 11:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/images/profile_images/default-product-image.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
